/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SortingAssignment;

import java.io.File;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author berd1810
 */
public class SortingAssignment extends javax.swing.JFrame {

    SortingTime sort;
    long insertion, quick, bubble, selection;
    ArrayList<Integer> Arrsml = new ArrayList<>();
     ArrayList<Integer> Arrbig = new ArrayList<>();
      ArrayList<Integer> Arrmd = new ArrayList<>();

           NumberFormat nf = NumberFormat.getInstance();
       
    public SortingAssignment() {
        initComponents();
        try {

            Scanner s = new Scanner(new File("smalldataset.txt"));
            while (s.hasNext()) {
                Arrsml.add(s.nextInt());
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        try {

            Scanner s = new Scanner(new File("medset.txt"));
            while (s.hasNext()) {
                Arrmd.add(s.nextInt());
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        
          try {

            Scanner s = new Scanner(new File("largedataset.txt"));
            while (s.hasNext()) {
                Arrbig.add(s.nextInt());
            }
        } catch (IOException e) {
            System.out.println(e);
        }
        
        
        

        sort = new SortingTime();
        sort.setData(Arrsml);
        sdsbtn.setSelected(true);
        
   
         nf.setMaximumFractionDigits(8);            
        nf.setGroupingUsed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdsbtn = new javax.swing.JRadioButton();
        ldsbtn = new javax.swing.JRadioButton();
        insertionBtn = new javax.swing.JButton();
        selectionBtn = new javax.swing.JButton();
        BubbleBtn = new javax.swing.JButton();
        QuicksortBtn = new javax.swing.JButton();
        insertionField = new javax.swing.JTextField();
        selectionField = new javax.swing.JTextField();
        BubbleField = new javax.swing.JTextField();
        quickField = new javax.swing.JTextField();
        mdsbtn = new javax.swing.JRadioButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sdsbtn.setText("Small Data Set");
        sdsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdsbtnActionPerformed(evt);
            }
        });

        ldsbtn.setText("Large Data Set");
        ldsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldsbtnActionPerformed(evt);
            }
        });

        insertionBtn.setText("Insertion");
        insertionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertionBtnActionPerformed(evt);
            }
        });

        selectionBtn.setText("Selection");
        selectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionBtnActionPerformed(evt);
            }
        });

        BubbleBtn.setText("Bubble");
        BubbleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubbleBtnActionPerformed(evt);
            }
        });

        QuicksortBtn.setText("Quicksort");
        QuicksortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuicksortBtnActionPerformed(evt);
            }
        });

        mdsbtn.setText("Medium Data Set");
        mdsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdsbtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(insertionBtn)
                        .addGap(34, 34, 34)
                        .addComponent(insertionField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectionBtn)
                            .addComponent(BubbleBtn)
                            .addComponent(QuicksortBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quickField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(BubbleField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ldsbtn)
                                .addGap(13, 13, 13)
                                .addComponent(mdsbtn)
                                .addGap(18, 18, 18)
                                .addComponent(sdsbtn)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdsbtn)
                    .addComponent(ldsbtn)
                    .addComponent(mdsbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertionBtn)
                    .addComponent(insertionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionBtn)
                    .addComponent(selectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BubbleBtn)
                    .addComponent(BubbleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuicksortBtn)
                    .addComponent(quickField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdsbtnActionPerformed

        ldsbtn.setSelected(false);
        mdsbtn.setSelected(false);
        sort.setData(Arrsml);


    }//GEN-LAST:event_sdsbtnActionPerformed

    private void insertionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertionBtnActionPerformed

        insertion = sort.insertionSort();
        float insertionFloat = ((float)insertion/1000000);
        //convert nanosec to milisec
        
        
        insertionField.setText(nf.format(insertionFloat)+"ms");
        //nf format so that it does not put the very small numbers in scientific notation.
        
        
        


    }//GEN-LAST:event_insertionBtnActionPerformed

    private void QuicksortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuicksortBtnActionPerformed
        
       long point1 = System.nanoTime();
       sort.quick(0,sort.returnData().size()-1);
       long point2= System.nanoTime();
       
       float quickFloat = ((float)(point2-point1)/1000000);
       quickField.setText(nf.format(quickFloat)+"ms");
       
        
        
        
    }//GEN-LAST:event_QuicksortBtnActionPerformed

    private void ldsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldsbtnActionPerformed
        sdsbtn.setSelected(false);
        mdsbtn.setSelected(false);
        sort.setData(Arrbig);


    }//GEN-LAST:event_ldsbtnActionPerformed

    private void selectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionBtnActionPerformed
        selection = sort.selectionSort();
        float selectionFloat = ((float)selection/1000000);
        selectionField.setText(nf.format(selectionFloat)+"ms");
    }//GEN-LAST:event_selectionBtnActionPerformed

    private void BubbleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubbleBtnActionPerformed
        bubble = sort.selectionSort();

        float bubbleFloat = ((float)bubble/1000000);
        BubbleField.setText(nf.format(bubbleFloat)+"ms");

    }//GEN-LAST:event_BubbleBtnActionPerformed

    private void mdsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdsbtnActionPerformed

        sdsbtn.setSelected(false);
        ldsbtn.setSelected(false);
        sort.setData(Arrmd);

    }//GEN-LAST:event_mdsbtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortingAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortingAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortingAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortingAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortingAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BubbleBtn;
    private javax.swing.JTextField BubbleField;
    private javax.swing.JButton QuicksortBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton insertionBtn;
    private javax.swing.JTextField insertionField;
    private javax.swing.JRadioButton ldsbtn;
    private javax.swing.JRadioButton mdsbtn;
    private javax.swing.JTextField quickField;
    private javax.swing.JRadioButton sdsbtn;
    private javax.swing.JButton selectionBtn;
    private javax.swing.JTextField selectionField;
    // End of variables declaration//GEN-END:variables
}
