/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arraylists;

import static arraylists.Hungergames.names;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author berd1810
 */
public class unitAssignmentForm extends javax.swing.JFrame {

    static String firstName, lastName;
    //variables we will be using for generating the user's username

    static String textName;
    //temporary variable we'll be using to get names from the text file

    static ArrayList<String> usernames = new ArrayList<>();
    //the arraylsit we will be adding usernames to

    static ArrayList<String> usedNames = new ArrayList<>();
    //the array list  created from the text file that already has predetermined names in it.

    /**
     * Creates new form unitAssignmentForm
     */
    public unitAssignmentForm() {
        initComponents();
        getNames();
        generateusernameforTextFile();
    }

    public void getNames() {
        //extracting first and last name from the text file. We will split it into 2 components afterwards
        try {

            String fileName = "names.txt";
            String filePath = new File("").getAbsolutePath(); //find the directory of the project
            File file = new File(filePath + "\\" + fileName);
            System.out.println(filePath + fileName);
            Scanner s = new Scanner(file);

            while (s.hasNextLine()) {

                usedNames.add(s.nextLine());

            }

        } catch (Exception e2) {
            System.out.println(e2);
        }

    }

    public static void generateusernameforTextFile() {

        //method that generates usernames depending on the first and last name from the text file
        for (int i = 0; i < usedNames.size(); i++) {
            int count=1;
            textName = usedNames.get(i);
            String[] firstandlastname = textName.split(",");
            //2 String values will be stored in a temporary array

            String username = firstandlastname[1] + firstandlastname[0].substring(0, count);
            //index at 1 is the last name, and at 0 is the first name and we are combining lastname and the first letter of the first name
            
            
            
            //check if the generated username already exists in the usedNames arraylist. If it does it will increase the amount of letters it has to put after the last name to avoid repetition.
            while(true){
            if(usedNames.contains(username)){
                count++;
                username = firstandlastname[1] + firstandlastname[0].substring(0, count);
          
            }
            
            else{
            
            usedNames.set(i, username);
            count=0;
            break;
            }
            
            }
        }

        


//            if (usernames.contains(generatedUsernames[i])) {
//
//            } else {
//                usernames.add(generatedUsernames[i].toLowerCase());
//                selectedUsernameField.setText(generatedUsernames[i].toLowerCase());
//                usernamesTextArea.append(generatedUsernames[i].toLowerCase() + "\n");
//
//                break;
//            }
        
        for (int i = 0; i < usedNames.size(); i++) {

            usernames.add(usedNames.get(i));
            usernames.set(i, usernames.get(i).toLowerCase());
            

            //add the username we've generated to the usernames arraylist

        }

        for (int i = 0; i < usedNames.size(); i++) {
            usernamesTextArea.append(usernames.get(i) + "\n");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usernamesTextArea = new javax.swing.JTextArea();
        selectedUsernameField = new javax.swing.JTextField();
        closeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        generatedArea = new javax.swing.JTextArea();
        generatedUsernamesLbl = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        firstNamelbl = new javax.swing.JLabel();
        lastNamelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernamesTextArea.setEditable(false);
        usernamesTextArea.setColumns(20);
        usernamesTextArea.setRows(5);
        jScrollPane1.setViewportView(usernamesTextArea);

        selectedUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedUsernameFieldActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        generatedArea.setEditable(false);
        generatedArea.setColumns(20);
        generatedArea.setRows(5);
        jScrollPane2.setViewportView(generatedArea);

        generatedUsernamesLbl.setText("Generated Usernames");

        generateBtn.setText("Generate ");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        firstNamelbl.setText("First Name");

        lastNamelbl.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(selectedUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(closeBtn)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateBtn)
                            .addComponent(generatedUsernamesLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNamelbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNamelbl)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNamelbl)
                    .addComponent(lastNamelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generatedUsernamesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectedUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(closeBtn)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectedUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedUsernameFieldActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed

        generatedArea.setText("");
        selectedUsernameField.setText("");

        firstName = firstNameField.getText().toLowerCase();
        lastName = lastNameField.getText().toLowerCase();
        


        String[] generatedUsernames;

        int amountofgeneratedUsernames = firstName.length();
        generatedUsernames = new String[amountofgeneratedUsernames];
        for (int i = 0; i < generatedUsernames.length; i++) {

            generatedUsernames[i] = lastName + firstName.substring(0, i + 1);
            //generating the username

        }

        for (int i = 0; i < generatedUsernames.length; i++) {

            generatedArea.append(generatedUsernames[i].toLowerCase() + "\n");
            //add these usernames to generated usernames area

        }

        //check for duplicates in the arraylist
        for (int i = 0; i < generatedUsernames.length; i++) {

            if (usernames.contains(generatedUsernames[i])) {

            } else {
                usernames.add(generatedUsernames[i].toLowerCase());
                selectedUsernameField.setText(generatedUsernames[i].toLowerCase());
                usernamesTextArea.append(generatedUsernames[i].toLowerCase() + "\n");

                break;
            }
        }


    }//GEN-LAST:event_generateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unitAssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unitAssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unitAssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unitAssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unitAssignmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNamelbl;
    private javax.swing.JButton generateBtn;
    private javax.swing.JTextArea generatedArea;
    private javax.swing.JLabel generatedUsernamesLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNamelbl;
    private javax.swing.JTextField selectedUsernameField;
    public static javax.swing.JTextArea usernamesTextArea;
    // End of variables declaration//GEN-END:variables
}
